name: Deploy static site to Azure Web App - exolab2025

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Azure Web App (public folder)
        uses: azure/webapps-deploy@v3
        with:
          app-name: exolab2025
          slot-name: production
          package: ./public
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
